// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package client

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson86ac526dDecodeGoArwosOrgCasperClient(in *jlexer.Lexer, out *RenewalRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "force":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Force = bool(in.Bool())
			}
		case "domain":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Domain = string(in.String())
			}
		case "format":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Format = RenewalFormat(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86ac526dEncodeGoArwosOrgCasperClient(out *jwriter.Writer, in RenewalRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"force\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Force))
	}
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix)
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"format\":"
		out.RawString(prefix)
		out.String(string(in.Format))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RenewalRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86ac526dEncodeGoArwosOrgCasperClient(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RenewalRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86ac526dEncodeGoArwosOrgCasperClient(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RenewalRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86ac526dDecodeGoArwosOrgCasperClient(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RenewalRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86ac526dDecodeGoArwosOrgCasperClient(l, v)
}
func easyjson86ac526dDecodeGoArwosOrgCasperClient1(in *jlexer.Lexer, out *RenewalModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = RenewalStatus(in.String())
			}
		case "format":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Format = RenewalFormat(in.String())
			}
		case "ca":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CA = string(in.String())
			}
		case "cert":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cert = string(in.String())
			}
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86ac526dEncodeGoArwosOrgCasperClient1(out *jwriter.Writer, in RenewalModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"format\":"
		out.RawString(prefix)
		out.String(string(in.Format))
	}
	if in.CA != "" {
		const prefix string = ",\"ca\":"
		out.RawString(prefix)
		out.String(string(in.CA))
	}
	if in.Cert != "" {
		const prefix string = ",\"cert\":"
		out.RawString(prefix)
		out.String(string(in.Cert))
	}
	if in.Key != "" {
		const prefix string = ",\"key\":"
		out.RawString(prefix)
		out.String(string(in.Key))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RenewalModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86ac526dEncodeGoArwosOrgCasperClient1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RenewalModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86ac526dEncodeGoArwosOrgCasperClient1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RenewalModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86ac526dDecodeGoArwosOrgCasperClient1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RenewalModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86ac526dDecodeGoArwosOrgCasperClient1(l, v)
}
