ver: "2"
packages:
    - package: casper
      source: casper
      version: git
      architecture:
        - amd64
        - arm64
      maintainer: The OSSPkg Team <github@osspkg.com>
      homepage: https://casper.osspkg.com/
      description:
        - Certificate Management Server
      section: utils
      priority: optional
      control:
        depends:
            - systemd
            - ca-certificates
            - casper-cli
        build: goppy build --arch=%arch%
        conffiles:
            - /etc/casper/config.yaml
        preinst: scripts/preinst.sh
        postinst: scripts/postinst.sh
        prerm: scripts/prerm.sh
        postrm: scripts/postrm.sh
      data:
        bin/casper-server: build/casper-server_%arch%
        etc/casper/config.yaml: config/config.yaml

    - package: casper-cli
      source: casper-cli
      version: git
      architecture:
        - amd64
        - arm64
      maintainer: The OSSPkg Team <github@osspkg.com>
      homepage: https://casper.osspkg.com/
      description:
        - Client for Certificate Management Server
      section: utils
      priority: optional
      control:
        depends:
          - ca-certificates
        build: goppy build --arch=%arch%
      data:
        bin/casper-cli: build/casper-cli_%arch%
