ver: "2"
packages:
    - package: casper-server
      source: casper-server
      version: git
      architecture:
        - amd64
        - arm64
      maintainer: The OSSPkg Team <github@osspkg.com>
      homepage: https://casper.osspkg.com/
      description:
        - Casper Certificate Management Server
      section: utils
      priority: optional
      control:
        depends:
            - systemd
            - ca-certificates
            - casper-cli
        build: goppy build --arch=%arch% --mode=app --main=casper-server
        conffiles:
            - /etc/casper/server.yaml
        preinst: scripts/casper-server_preinst.sh
        postinst: scripts/casper-server_postinst.sh
        prerm: scripts/casper-server_prerm.sh
        postrm: scripts/casper-server_postrm.sh
      data:
        bin/casper-server: build/casper-server_%arch%
        etc/systemd/system/casper-server.service: init/casper-server.service
        etc/casper/server.yaml: config/server.yaml
        var/lib/casper/generate.sh: scripts/generate.sh
        var/lib/casper/migrations: "d:migrations"

    - package: casper-cli
      source: casper-cli
      version: git
      architecture:
        - amd64
        - arm64
      maintainer: The OSSPkg Team <github@osspkg.com>
      homepage: https://casper.osspkg.com/
      description:
        - Client for Casper Certificate Management Server
      section: utils
      priority: optional
      control:
        depends:
          - systemd
          - ca-certificates
        build: goppy build --arch=%arch% --mode=app --main=casper-cli
        conffiles:
          - /etc/casper/client.yaml
        preinst: scripts/casper-cli_preinst.sh
        postinst: scripts/casper-cli_postinst.sh
        prerm: scripts/casper-cli_prerm.sh
        postrm: scripts/casper-cli_postrm.sh
      data:
        bin/casper-cli: build/casper-cli_%arch%
        etc/systemd/system/casper-cli.service: init/casper-cli.service
        etc/casper/client.yaml: config/client.yaml
